### ISSUE TITLE
Release for Plone 5 needed!

### ISSUE THREAD

**Issue by jensens** [collective/Products.RedirectionTool#6]
please a release! or give me access, so i do.

**Comment by vangheem** [comment]
@ggozad @hannosch @erikrose @wichert @fschulze ^^^

**Comment by tkimnguyen** [comment]
We need to fix these kinds of release permissions problems :)

**Comment by ggozad** [comment]
Yo!
Away but can fix tomorrow :) let me know to which id I give permissions and whether I should remive the rest of us

**Comment by vangheem** [comment]
You can add "vangheem" as an owner. Anyone know what the collective account is for fallback ownership?

**Comment by gforcada** [comment]
@tkimnguyen always give the user "plone" access to them and then the @plone/release-team will be able to do releases as well (or to add more users access to them).

**Comment by ggozad** [comment]
Have added both @vangheem as well as plone as owners. Feel free to remove people like me who are inactive.

**Comment by vangheem** [comment]
done: https://pypi.python.org/pypi/Products.RedirectionTool/1.4.0

**Comment by tkimnguyen** [comment]
Thx for the pointer @gforcada! And hi @ggozad :)
